[package]
name = "tique"
version = "0.1.0"
authors = ["Caio RomÃ£o <contact@caio.co>"]
edition = "2018"

[dependencies]
tantivy = "0.10"
serde = { version = "1", features = ["derive"] }
byteorder = "1.3"
nom = "5"

[dev-dependencies]
zerocopy = "0.2"
rand = "0.7"
