[package]
name = "cantine"
version = "0.1.0"
authors = ["Caio Rom√£o <contact@caio.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1"
byteorder = "1.3"
crossbeam-channel = "0.3"
memmap = "0.7"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3", default-features = false }
tantivy = "0.10"
tempfile = "3"
zerocopy = "0.2"
